---
env:
  env_parameter: root-level

# Access environment variables defined in a file that was passed to cirrus using
# `--env-file`.
first_task:
  container:
    image: alpine:3.16
  first_test_script:
    - "cat /etc/os-release"
    - "echo environment variables set by --env-file: $username/$password"

# Access environment variable passed to cirrus from the command line using `-e`,
# or set at the root/task level. Note: setting an environment variable at task
# level takes precendece over root level.
second_task:
  env:
    env_parameter: task-level
  container:
    image: alpine:3.17
  second_test_script:
    - "cat /etc/os-release"
    - "echo environment variable set by -e or at root/task level: $env_parameter"
